
spring.application.name=sigap-backend

# =========================
# VARIABLES DE ENTORNO
# =========================

spring.config.import=optional:file:.env[.properties]


# =========================
# BASE DE DATOS
# =========================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# =========================
# JPA / HIBERNATE
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# =========================
# SERVIDOR
# =========================

server.port=8080